block.settings.dc_chatbot_block:
  type: block_settings
  label: 'Drupal Cloud Chatbot block'
  mapping:
    button_text:
      type: label
      label: 'Button text'
    button_position:
      type: string
      label: 'Button position'
    button_color:
      type: string
      label: 'Button color'
    show_on_mobile:
      type: boolean
      label: 'Show on mobile'
    trigger_delay:
      type: integer
      label: 'Trigger delay'

dc_chatbot.settings:
  type: config_object
  label: 'Drupal Cloud Chatbot settings'
  mapping:
    api_key:
      type: string
      label: 'API key'
    api_url:
      type: string
      label: 'Next.js API URL'
