_core:
  default_config_hash: HlN7eAN2N4JIHsYv56V4E7sqC9bS609KwvGFjyD_mgk
langcode: en
uuid: 1050e6ce-0be3-498d-9d26-cb28a4a076d4
name: 'Drupal Cloud Site'
mail: noreply@example.com
slogan: ''
page:
  403: ''
  404: ''
  front: /dcloud-config
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
